[project]
name = "fileglancer-hub"
version = "0.1.0"
description = "Fileglancer deployment"
authors = [
    "Allison Truhlar <truhlara@janelia.hhmi.org>",
    "Jody Clements <clementsj@janelia.hhmi.org>",
    "Cristian Goina <goinac@janelia.hhmi.org>",
    "Konrad Rokicki <rokickik@janelia.hhmi.org>"
]
channels = ["conda-forge"]
platforms = ["linux-64"]
preview = ["pixi-build"]

[dependencies]
python = "*"
pip = "*"

[tasks]
start = "uvicorn fileglancer.app:app --host 127.0.0.1 --workers 10 --port 8989 --no-access-log"

[pypi-dependencies]
fileglancer = "==2.0.2"
