[project]
name = "fileglancer-hub"
version = "0.0.1"
description = "JupyterHub integration for Fileglancer"
authors = ["Jody Clements <clementsj@janelia.hhmi.org>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64"]
preview = ["pixi-build"]

[tasks]
start = "python hub_launcher.py"

[dependencies]
python = "*"
pip = "*"

[feature.hub.dependencies]
jupyterlab = ">=4.4.2"
jupyterhub = ">=5.3.0"

[feature.hub.pypi-dependencies]
fileglancer = "*"

[feature.central.pypi-dependencies]
fileglancer-central = "*"

[environments]
hub = { features = ["hub"], solve-group = "hub" }
central = { features = ["central"], solve-group = "central" }
